FROM node:20-alpine

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем исходный код
COPY . .

# Открываем порт Vite
EXPOSE 5173

# Запускаем в режиме разработки с флагом --host, чтобы Docker видел сайт
CMD ["npm", "run", "dev", "--", "--host"]