from __future__ import annotations

from typing import Any


categories: list[dict[str, Any]] = [
    {
        "slug": "paints",
        "name": "Краски",
        "description": "Акварель, гуашь, акрил и масло для любой техники.",
        "image": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80",
    },
    {
        "slug": "brushes",
        "name": "Кисти",
        "description": "Мягкие и упругие кисти для акварели, масла и акрила.",
        "image": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=80",
    },
    {
        "slug": "paper",
        "name": "Бумага",
        "description": "Скетчбуки и профессиональная бумага разных фактур.",
        "image": "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80",
    },
    {
        "slug": "pencils",
        "name": "Карандаши",
        "description": "Графит, цветные и пастельные карандаши.",
        "image": "https://images.unsplash.com/photo-1449247613801-ab06418e2861?auto=format&fit=crop&w=1200&q=80",
    },
    {
        "slug": "sets",
        "name": "Наборы",
        "description": "Готовые комплекты для начинающих и подарков.",
        "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80",
    },
    {
        "slug": "easels",
        "name": "Мольберты",
        "description": "Настольные и напольные мольберты для дома и студии.",
        "image": "https://images.unsplash.com/photo-1513366208864-87536b8bd7b4?auto=format&fit=crop&w=1200&q=80",
    },
]

products: list[dict[str, Any]] = [
    {
        "id": 1,
        "slug": "aquarelle-lumiere-24",
        "name": "Акварель Lumiere, 24 цвета",
        "category": "paints",
        "brand": "Lumiere",
        "type": "Акварель",
        "color": "Мульти",
        "price": 2890.0,
        "old_price": 3190.0,
        "rating": 4.9,
        "popularity": 95,
        "in_stock": True,
        "tags": ["хит", "новичкам"],
        "images": [
            "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1453738773917-9c3eff1db985?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "Набор профессиональной акварели с чистыми пигментами и мягкими переходами.",
        "details": [
            "Высокая концентрация пигмента",
            "Плавная растяжка цвета",
            "Компактный металлический кейс",
        ],
        "technical": {
            "Светостойкость": "ASTM I-II",
            "Связующее": "Гуммиарабик",
            "Страна": "Франция",
        },
        "related_ids": [6, 11, 13],
    },
    {
        "id": 2,
        "slug": "acrylic-atelier-12",
        "name": "Акрил Atelier, 12 тюбиков",
        "category": "paints",
        "brand": "Atelier",
        "type": "Акрил",
        "color": "Мульти",
        "price": 2190.0,
        "old_price": None,
        "rating": 4.8,
        "popularity": 89,
        "in_stock": True,
        "tags": ["универсально"],
        "images": [
            "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "Плотный акрил с бархатистым матовым финишем для холста и дерева.",
        "details": [
            "Быстрое высыхание",
            "Устойчивый матовый слой",
            "Хорошая укрывистость",
        ],
        "technical": {
            "Светостойкость": "Высокая",
            "Основа": "Водная",
            "Финиш": "Матовый",
        },
        "related_ids": [7, 14, 16],
    },
    {
        "id": 3,
        "slug": "oil-heritage-10",
        "name": "Масло Heritage, базовая палитра",
        "category": "paints",
        "brand": "Heritage",
        "type": "Масло",
        "color": "Мульти",
        "price": 3390.0,
        "old_price": 3690.0,
        "rating": 4.7,
        "popularity": 77,
        "in_stock": True,
        "tags": ["классика"],
        "images": [
            "https://images.unsplash.com/photo-1513366208864-87536b8bd7b4?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1453738773917-9c3eff1db985?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "Традиционные масляные краски с насыщенными пигментами и густой текстурой.",
        "details": [
            "Классическая льняная связка",
            "Глубокая насыщенность",
            "Подходит для лессировок",
        ],
        "technical": {
            "Светостойкость": "Отличная",
            "Связующее": "Льняное масло",
            "Вязкость": "Средняя",
        },
        "related_ids": [7, 9, 16],
    },
    {
        "id": 4,
        "slug": "brush-sable-round-4",
        "name": "Кисть колонок Round №4",
        "category": "brushes",
        "brand": "SableArt",
        "shape": "Круглая",
        "size": "4",
        "color": "Натуральный",
        "price": 890.0,
        "old_price": None,
        "rating": 4.9,
        "popularity": 93,
        "in_stock": True,
        "tags": ["хит"],
        "images": [
            "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "Тонкая управляемая кисть для акварели и детализации.",
        "details": [
            "Острый кончик",
            "Высокая эластичность волоса",
            "Лёгкая деревянная ручка",
        ],
        "technical": {
            "Материал": "Колонок",
            "Форма": "Круглая",
            "Размер": "№4",
        },
        "related_ids": [1, 6, 11],
    },
    {
        "id": 5,
        "slug": "brush-synthetic-flat-12",
        "name": "Кисть синтетика Flat №12",
        "category": "brushes",
        "brand": "Forma",
        "shape": "Плоская",
        "size": "12",
        "color": "Белый",
        "price": 640.0,
        "old_price": None,
        "rating": 4.6,
        "popularity": 70,
        "in_stock": True,
        "tags": ["акрил"],
        "images": [
            "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "Плоская кисть для заливок и широких мазков акрилом и гуашью.",
        "details": [
            "Упругая синтетика",
            "Долговечная обойма",
            "Равномерный набор краски",
        ],
        "technical": {
            "Материал": "Синтетика",
            "Форма": "Плоская",
            "Размер": "№12",
        },
        "related_ids": [2, 7, 14],
    },
    {
        "id": 6,
        "slug": "paper-cotton-300-a4",
        "name": "Бумага Cotton 300 г/м², A4",
        "category": "paper",
        "brand": "PaperSoul",
        "type": "Акварельная",
        "color": "Кремовый",
        "price": 1150.0,
        "old_price": None,
        "rating": 4.8,
        "popularity": 90,
        "in_stock": True,
        "tags": ["профи"],
        "images": [
            "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1449247613801-ab06418e2861?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "100% хлопок, холодный пресс, идеально для многослойной акварели.",
        "details": [
            "Фактура cold press",
            "Не коробится от воды",
            "Плотность 300 г/м²",
        ],
        "technical": {
            "Состав": "100% хлопок",
            "Плотность": "300 г/м²",
            "Фактура": "Среднее зерно",
        },
        "related_ids": [1, 4, 11],
    },
    {
        "id": 7,
        "slug": "canvas-pad-a3",
        "name": "Холст на картоне A3",
        "category": "paper",
        "brand": "StudioBase",
        "type": "Холст",
        "color": "Белый",
        "price": 990.0,
        "old_price": 1190.0,
        "rating": 4.5,
        "popularity": 65,
        "in_stock": True,
        "tags": ["акрил", "масло"],
        "images": [
            "https://images.unsplash.com/photo-1513366208864-87536b8bd7b4?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "Грунтованный холст на картоне для этюдов и учебных работ.",
        "details": [
            "3 панели в комплекте",
            "Ровный заводской грунт",
            "Подходит для акрила и масла",
        ],
        "technical": {
            "Плотность": "380 г/м²",
            "Основа": "Картон",
            "Грунт": "Акриловый",
        },
        "related_ids": [2, 3, 5],
    },
    {
        "id": 8,
        "slug": "graphite-set-12",
        "name": "Набор графитовых карандашей 12 шт",
        "category": "pencils",
        "brand": "GraphOne",
        "hardness": "2H-8B",
        "type": "Графит",
        "color": "Графит",
        "price": 790.0,
        "old_price": None,
        "rating": 4.8,
        "popularity": 86,
        "in_stock": True,
        "tags": ["скетч"],
        "images": [
            "https://images.unsplash.com/photo-1449247613801-ab06418e2861?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "Полный диапазон твердости для штриховки, построения и тональной работы.",
        "details": [
            "От 2H до 8B",
            "Ударопрочный грифель",
            "Металлический футляр",
        ],
        "technical": {
            "Твердость": "2H-8B",
            "Диаметр грифеля": "2 мм",
            "Страна": "Германия",
        },
        "related_ids": [10, 12, 15],
    },
    {
        "id": 9,
        "slug": "pastel-pencils-24",
        "name": "Пастельные карандаши 24 цвета",
        "category": "pencils",
        "brand": "ColorNest",
        "hardness": "Soft",
        "type": "Пастель",
        "color": "Мульти",
        "price": 1690.0,
        "old_price": 1890.0,
        "rating": 4.7,
        "popularity": 74,
        "in_stock": True,
        "tags": ["портрет"],
        "images": [
            "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1449247613801-ab06418e2861?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "Мягкая пастель в формате карандаша для портретов и текстур.",
        "details": [
            "Плавная растушевка",
            "Интенсивные оттенки",
            "Низкое крошение",
        ],
        "technical": {
            "Твердость": "Soft",
            "Связующее": "Пастельное",
            "Количество": "24",
        },
        "related_ids": [10, 12, 16],
    },
    {
        "id": 10,
        "slug": "sketchbook-linen-a5",
        "name": "Скетчбук Linen A5, 120 листов",
        "category": "paper",
        "brand": "SketchLeaf",
        "type": "Скетчбук",
        "color": "Слоновая кость",
        "price": 1250.0,
        "old_price": None,
        "rating": 4.9,
        "popularity": 97,
        "in_stock": True,
        "tags": ["ежедневник", "хит"],
        "images": [
            "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1449247613801-ab06418e2861?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "Скетчбук с льняной обложкой и теплой бумагой для графики и маркеров.",
        "details": [
            "Плотность 160 г/м²",
            "Твердый переплет",
            "Лента-закладка",
        ],
        "technical": {
            "Формат": "A5",
            "Плотность": "160 г/м²",
            "Листов": "120",
        },
        "related_ids": [8, 9, 12],
    },
    {
        "id": 11,
        "slug": "beginner-watercolor-kit",
        "name": "Набор для начинающих «Акварельный старт»",
        "category": "sets",
        "brand": "Artistic",
        "type": "Набор новичка",
        "color": "Мульти",
        "price": 4590.0,
        "old_price": 5190.0,
        "rating": 4.9,
        "popularity": 99,
        "in_stock": True,
        "tags": ["новичкам", "подарок"],
        "images": [
            "https://images.unsplash.com/photo-1453738773917-9c3eff1db985?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "Готовый набор: краски, кисти, бумага и видео-гайд для первого месяца занятий.",
        "details": [
            "24 акварельных кюветы",
            "3 кисти разных размеров",
            "Альбом 20 листов",
        ],
        "technical": {
            "Уровень": "Начинающий",
            "Комплектация": "Полная",
            "Бонус": "Онлайн-урок",
        },
        "related_ids": [1, 4, 6],
    },
    {
        "id": 12,
        "slug": "gift-certificate-5000",
        "name": "Подарочный сертификат 5000 ₽",
        "category": "sets",
        "brand": "Artistic",
        "type": "Сертификат",
        "color": "Лавандовый",
        "price": 5000.0,
        "old_price": None,
        "rating": 5.0,
        "popularity": 84,
        "in_stock": True,
        "tags": ["подарок"],
        "images": [
            "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "Электронный и печатный формат сертификата с нежным художественным дизайном.",
        "details": [
            "Доставка на email",
            "Срок действия 12 месяцев",
            "Можно доплачивать бонусами",
        ],
        "technical": {
            "Номинал": "5000 ₽",
            "Формат": "PDF + печатный",
            "Срок": "12 месяцев",
        },
        "related_ids": [11, 15, 9],
    },
    {
        "id": 13,
        "slug": "easel-table-oak",
        "name": "Мольберт настольный Oak Mini",
        "category": "easels",
        "brand": "WoodForm",
        "type": "Настольный",
        "color": "Дуб",
        "price": 2490.0,
        "old_price": None,
        "rating": 4.7,
        "popularity": 76,
        "in_stock": True,
        "tags": ["компакт"],
        "images": [
            "https://images.unsplash.com/photo-1513366208864-87536b8bd7b4?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1453738773917-9c3eff1db985?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "Компактный настольный мольберт для дома и учебы.",
        "details": [
            "Складная конструкция",
            "Регулировка угла наклона",
            "Натуральный дуб",
        ],
        "technical": {
            "Материал": "Дуб",
            "Высота": "42 см",
            "Макс. формат": "A3",
        },
        "related_ids": [1, 6, 10],
    },
    {
        "id": 14,
        "slug": "gouache-soft-16",
        "name": "Гуашь SoftTone, 16 баночек",
        "category": "paints",
        "brand": "SoftTone",
        "type": "Гуашь",
        "color": "Пастель",
        "price": 1490.0,
        "old_price": None,
        "rating": 4.6,
        "popularity": 69,
        "in_stock": True,
        "tags": ["пастель"],
        "images": [
            "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "Матовая гуашь в приглушенной пастельной палитре.",
        "details": [
            "16 мягких оттенков",
            "Укрывистая текстура",
            "Легко смешивается",
        ],
        "technical": {
            "Светостойкость": "Средняя",
            "Финиш": "Матовый",
            "Объем": "20 мл",
        },
        "related_ids": [2, 5, 7],
    },
    {
        "id": 15,
        "slug": "gift-box-creative-evening",
        "name": "Подарочный бокс «Творческий вечер»",
        "category": "sets",
        "brand": "Artistic",
        "type": "Подарочный набор",
        "color": "Песочный",
        "price": 3290.0,
        "old_price": 3590.0,
        "rating": 4.8,
        "popularity": 88,
        "in_stock": True,
        "tags": ["подарок", "акция"],
        "images": [
            "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1453738773917-9c3eff1db985?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "Эстетичный подарочный набор со скетчбуком, маркерами и открыткой.",
        "details": [
            "Премиальная упаковка",
            "Персональная открытка",
            "Бесплатная доставка",
        ],
        "technical": {
            "Формат": "Подарочный",
            "Вес": "1.2 кг",
            "Упаковка": "Крафт-бокс",
        },
        "related_ids": [12, 10, 8],
    },
    {
        "id": 16,
        "slug": "easel-floor-studio",
        "name": "Мольберт напольный Studio Pro",
        "category": "easels",
        "brand": "WoodForm",
        "type": "Напольный",
        "color": "Бук",
        "price": 6890.0,
        "old_price": 7490.0,
        "rating": 4.9,
        "popularity": 81,
        "in_stock": True,
        "tags": ["студия"],
        "images": [
            "https://images.unsplash.com/photo-1513366208864-87536b8bd7b4?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=80",
        ],
        "description": "Профессиональный устойчивый мольберт для студии с колесами.",
        "details": [
            "Регулировка высоты",
            "Фиксаторы колес",
            "Лоток для инструментов",
        ],
        "technical": {
            "Материал": "Бук",
            "Высота": "до 210 см",
            "Макс. холст": "160 см",
        },
        "related_ids": [3, 7, 9],
    },
]

special_sections: list[dict[str, Any]] = [
    {
        "slug": "beginner-kits",
        "title": "Наборы для начинающих",
        "description": "Продуманные комплекты с понятным стартом и инструкциями.",
        "product_ids": [11, 8, 10],
        "image": "https://images.unsplash.com/photo-1453738773917-9c3eff1db985?auto=format&fit=crop&w=1200&q=80",
    },
    {
        "slug": "gift-ideas",
        "title": "Подарочные сертификаты и наборы",
        "description": "Красивые подарки, которые вдохновляют творить.",
        "product_ids": [12, 15, 1],
        "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80",
    },
]

home_slider: list[dict[str, str]] = [
    {
        "title": "Место, где рождаются идеи",
        "subtitle": "Премиальные материалы для живописи, скетчинга и вдохновения.",
        "image": "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1800&q=80",
        "cta": "Смотреть каталог",
        "cta_link": "/catalog",
    },
    {
        "title": "Нежные палитры, мягкий свет",
        "subtitle": "Собрали коллекцию приглушенных оттенков для уютной студии.",
        "image": "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?auto=format&fit=crop&w=1800&q=80",
        "cta": "Наборы для старта",
        "cta_link": "/specials",
    },
    {
        "title": "Подарки для творческих людей",
        "subtitle": "Сертификаты и готовые боксы с эстетичной упаковкой.",
        "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1800&q=80",
        "cta": "Выбрать подарок",
        "cta_link": "/specials",
    },
]

benefits: list[dict[str, str]] = [
    {
        "icon": "🚚",
        "title": "Бесплатная доставка",
        "description": "При заказе от 3500 ₽ по всей России.",
    },
    {
        "icon": "🎁",
        "title": "Подарок в каждом заказе",
        "description": "Маленький творческий бонус внутри коробки.",
    },
    {
        "icon": "🧑‍🎨",
        "title": "Подбор материалов",
        "description": "Поможем собрать набор под вашу технику.",
    },
    {
        "icon": "↩️",
        "title": "Лёгкий возврат",
        "description": "14 дней на обмен и возврат без сложностей.",
    },
]

promo_codes: dict[str, dict[str, Any]] = {
    "ARTSTART": {"type": "percent", "value": 10},
    "GIFT500": {"type": "fixed", "value": 500},
    "CREAM": {"type": "percent", "value": 7},
}

orders_demo: list[dict[str, Any]] = [
    {
        "id": "A-2025-0012",
        "date": "2025-12-18",
        "status": "Доставлен",
        "total": 5220.0,
        "items": [
            {"product_id": 1, "qty": 1},
            {"product_id": 4, "qty": 1},
            {"product_id": 6, "qty": 1},
        ],
    },
    {
        "id": "A-2026-0004",
        "date": "2026-01-28",
        "status": "В пути",
        "total": 3290.0,
        "items": [{"product_id": 15, "qty": 1}],
    },
]

favorites_demo: list[int] = [10, 11, 16]

account_demo: dict[str, Any] = {
    "name": "Анна Морозова",
    "email": "anna@example.com",
    "bonuses": 740,
}

contacts_info: dict[str, Any] = {
    "address": "Москва, ул. Артельная, 12",
    "phone": "+7 (495) 123-45-67",
    "email": "hello@artistic-shop.ru",
    "work_hours": "Ежедневно: 10:00-21:00",
    "map_embed": "https://www.openstreetmap.org/export/embed.html?bbox=37.6063%2C55.7488%2C37.6363%2C55.7688&layer=mapnik&marker=55.7588%2C37.6213",
    "photo": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
}

contact_messages: list[dict[str, Any]] = []
